config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"

  # resources :projects
  get    '/projects'         , to: 'projects#index'    , as: 'projects'
  post   '/projects'         , to: 'projects#create'
  get    '/projects/new'     , to: 'projects#new'      , as: 'new_project'
  get    '/projects/:id/edit', to: 'projects#edit'     , as: 'edit_project'
  get    '/projects/:id'     , to: 'projects#show'     , as: 'project'
  patch  '/projects/:id'     , to: 'projects#update'
  put    '/projects/:id'     , to: 'projects#update'
  delete '/projects/:id'     , to: 'projects#destroy'

  # resources :bugs
  get    '/bugs'          , to: 'bugs#index'  , as: 'bugs'
  post   '/bugs'          , to: 'bugs#create'
  get    '/bugs/new'      , to: 'bugs#new'    , as: 'new_bug'
  get    '/bugs/:id/edit' , to: 'bugs#edit'   , as: 'edit_bug'
  get    '/bugs/:id'      , to: 'bugs#show'   , as: 'bug'
  patch  '/bugs/:id'      , to: 'bugs#update'
  put    '/bugs/:id'      , to: 'bugs#update'
  delete '/bugs/:id'      , to: 'bugs#destroy'

  # resources :projects_users
  get    '/projectsusers'          , to: 'projectsusers#index'
  # post   '/projectsusers'          , to: 'projectsusers#create'
  get    '/projectsusers/new'      , to: 'projects_users#new'    , as: 'new_projectsusers'
  get    '/projectsusers/:id/edit' , to: 'projects_users#edit'   , as: 'edit_projectsusers'
  # get    '/projectsusers/:id'      , to: 'projectsusers#show'   , as: 'projectsusers'
  # patch  '/projectsusers/:id'      , to: 'projectsusers#update'
  # put    '/projectsusers/:id'      , to: 'projectsusers#update'
  # delete '/projectsusers/:id'      , to: 'projectsusers#destroy'


  get '/:slug', to: 'pages#errorpage'
  get '/:slug/:slug2', to: 'pages#errorpage'
  get '/:slug/:slug2/:slug3', to: 'pages#errorpage'

  # get 'bugs/index'
  # get 'bugs/edit'
  # get 'bugs/show'
  # get 'bugs/update'
  # get 'bugs/destroy'
  # get 'bugs/create'
  # get 'projects/index'
  # get 'projects/edit'
  # get 'projects/show'
  # get 'projects/update'
  # get 'projects/destroy'
  # get 'projects/create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :deadline, presence: true
  validates :bug_type, presence: true
  validates :status, presence: true

  belongs_to :project
  belongs_to :creator, class_name: "User"
  belongs_to :solver, class_name: "User"
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true, length: { maximum: 200 }

  belongs_to :manager, class_name: "User"

  has_many :bugs
  has_and_belongs_to_many :users
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :creator_id_bugs, class_name: "Bug", foreign_key: "creator_id"
  has_many :solver_id_bugs, class_name: "Bug", foreign_key: "solver_id"

  has_many :created_projects, class_name: "Project", foreign_key: "manager_id"

  has_and_belongs_to_many :projects

  def manager?
    user_type == 'Manager'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :user_type, :email, :password) }
    
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :user_type, :email, :password, :current_password) }
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def index
    @bugs = Bug.all
  end

  def new
    puts "-------------------------------- "
    puts "Sample String"
    puts "-------------------------------- "
    @usernames = User.pluck(:username)
    @project_titles = Project.pluck(:title)
    @bug = Bug.new
  end

  def edit
    if Bug.exists?(params[:id])
      @usernames = User.pluck(:username)
      @project_titles = Project.pluck(:title)
      @bug = Bug.find(params[:id])
    else
      redirect_to new_bug_path
    end
  end

  def show
    @bug = Bug.find(params[:id])
  end

  def update
  end

  def destroy
  end

  def create
    bug_param = bug_params
    puts '------------------------------------------'
    puts bug_param
    puts '------------------------------------------'

    @bug = Bug.new(
      title: bug_param["title"],
      description: bug_param["description"],
      deadline: bug_param["deadline"],
      screenshot: bug_param["screenshot"],
      bug_type: bug_param["bug_type"],
      status: bug_param["status"],
      project_id: Project.where(title: bug_param["project_id"])[0].id,
      creator_id: User.where(username: bug_param["creator_id"])[0].id,
      solver_id: User.where(username: bug_param["solver_id"])[0].id
    )
    if @bug.save
      flash[:notice] = "Bug Was Created Succesully!"
      redirect_to bug_path(@bug)
    else
      render 'new'
    end
  end

  def testing
    @bug_params
  end

  private
    def bug_params
      params.require(:bug).permit(
        :title,
        :description,
        :deadline,
        :screenshot,
        :bug_type,
        :status,
        :project_id,
        :creator_id,
        :solver_id
      )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @users = User.all
    else
      @msg = "Sign in OR REGISTER TO SEE AVAILABLE OPTIONS"
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if current_user.manager?
      @projects = current_user.created_projects
    else
      @projects = current_user.projects
    end
  end

  def new
    print "-------------------------------- asdfasdf"
    @managers = (User.where(user_type:'Manager')).pluck(:username)
    @usernames = (User.where.not(user_type:'Manager')).pluck(:username)
    @project = Project.new
  end

  def edit
    if Project.exists?(params[:id])
      @managers = (User.where(user_type:'Manager')).pluck(:username)
      @usernames = (User.where.not(user_type:'Manager')).pluck(:username)
      @project = Project.find(params[:id])
    else
      flash[:alert] = "INVALID URL!"
      redirect_to root_path
    end
  end

  def show
    if Project.exists?(params[:id])
      @project = Project.find(params[:id])
    else
      flash[:alert] = "INVALID URL!"
      redirect_to root_path
    end
  end

  def update
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
  end

  def create
    flash[:notice] = "Bug Was Created Succesully!"
    redirect_to bug_path(@bug)
    project_params = project_form_params
    @project = Project.new(
      title: project_params["title"],
      description: project_params["description"],
      manager_id: User.where(username: project_params["manager_id"])[0].id,
      user_ids: User.where(username: project_params["user_ids"])[0].id
    )
    if @project.save
      flash[:notice] = "Project Was Created Succesully!"
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def testing
    @bug_params
  end

  private
    def project_form_params
      params.require(:project).permit(
        :title,
        :description,
        :manager_id,
        :user_ids
      )
    end
end

app/controllers/projects_users_controller.rb
class ProjectsUsersController < ApplicationController
  def index
  end

  def new
    puts '-------------------------------------'
    puts 'INT THE PROJEcTS USERS NEW DEF'
    puts '-------------------------------------'
    @usernames = User.pluck(:username)
    @project_titles = Project.pluck(:title)
    @project_user = ProjectsUser.new
  end

  def edit
    @usernames = User.pluck(:username)
    @project_titles = Project.pluck(:title)
    @project_user = ProjectsUser.find(params[:id])
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/projects_users_helper.rb
module ProjectsUsersHelper
end

app/views/bugs/_formBugs.html.erb
<%= form_for @bug do |f| %>
  <p>
    <%= f.label 'Title*' %>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :description %>
    <%= f.text_area :description, size: '70x7' %>
  </p>

  <p>
    <%= f.label 'Deadline*' %>
    <%= f.datetime_field :deadline %>
  </p>

  <p>
    <%= f.label :screenshot %>
    <%= f.file_field :screenshot %>
  </p>

  <p>
    <%= f.label 'Bug Type*' %>
    <%= f.select :bug_type, options_for_select(['Bug', 'Feature']) %>
  </p>

  <p>
    <%= f.label 'Status*' %>
    <%= f.select :status, options_for_select(['New', 'Started', 'Completed', 'Resolved']) %>
  </p>

  <p>
    <%= f.label 'Project ID*' %>
    <%= f.select :project_id, options_for_select(@project_titles) %>
  </p>

  <p>
    <%= f.label 'Creator*' %>
    <%= f.select :creator_id, options_for_select(@usernames) %>
  </p>

  <p>
    <%= f.label 'Solver*' %>
    <%= f.select :solver_id, options_for_select(@usernames) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/bugs/create.html.erb
<h1>Bugs#create</h1>
<p>Find me in app/views/bugs/create.html.erb</p>

app/views/bugs/destroy.html.erb
<h1>Bugs#destroy</h1>
<p>Find me in app/views/bugs/destroy.html.erb</p>

app/views/bugs/edit.html.erb
<h1>Bugs#edit</h1>
<p>Find me in app/views/bugs/edit.html.erb</p>

<%= render 'bugs/formBugs' %>

app/views/bugs/index.html.erb
<h1>Bugs#index</h1>
<p>Find me in app/views/bugs/index.html.erb</p>

app/views/bugs/new.html.erb
<h1>Bugs#new</h1>

<%= render 'bugs/formBugs' %>

app/views/bugs/show.html.erb
<h1>Bugs#show</h1>
<p>Find me in app/views/bugs/show.html.erb</p>

app/views/bugs/testing.html.erb
<%= @bug_params %>

app/views/bugs/update.html.erb
<h1>Bugs#update</h1>
<p>Find me in app/views/bugs/update.html.erb</p>

app/views/home/index.html.erb
<% if user_signed_in? %>
<h1>Signed in as "<%= current_user.username.capitalize %>"</h1>
  <% if current_user.user_type.capitalize == 'Manager' %>
    <button type="button" class="btn btn-info ml-auto"><a>Create Project</a></button>
    <h1>Manager</h1>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">User ID</th>
          <th scope="col">Username</th>
          <th scope="col">Email</th>
          <th scope="col">User Type</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row"><%= user.id %></th>
            <td><%= user.username.capitalize %></td>
            <td><%= user.email %></td>
            <td><%= user.user_type.capitalize %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% elsif current_user.user_type.capitalize == 'Developer' %>
    <%# <button type="button" class="btn btn-info">Create Project</button> %>
    <h1>Developer</h1>
  <% end %>
<% else %>
<h1><%= @msg%></h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTrackingSystem</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <% if notice %>
      <div class="alert alert-primary" role="alert">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <p class="notice"><%= alert %></p>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/projects/_formProjects.html.erb
<%= form_for @project do |f| %>
  <p>
    <%= f.label 'Title*' %>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label 'Manager*' %>
    <%= f.select :manager_id, options_for_select([current_user.username]) %>
  </p>

  <p>
    <%= f.label 'Add a user' %>
    <%= f.select :user_ids, options_for_select(@usernames), multiple: true %>
  </p>

  <%# <p> %>
    <%# <%= f.label 'Add Users' %> %>
    <%# <%= f.select :user_ids, options_from_collection_for_select(@usernames, 'id', 'name'), multiple: true %> %>
  <%# </p> %>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>

<%= render 'projects/formProjects' %>

<button type="button" class="btn btn-link">
  <%= link_to 'Main Page', root_path %>
</button>

app/views/projects/index.html.erb
<h1>Projects#index</h1>


<% if current_user.user_type.capitalize == 'Manager' %>
<%= link_to 'Create New Project', new_project_path, class: "btn btn-outline-secondary ml-auto" %>
<% end %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Project ID</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Manager</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <th scope="row"><%= project.id %></th>
      <td><%= link_to project.title, project_path(project) %></td>
      <td><%= project.description %></td>
      <td><%= project.manager.username.capitalize %></td>
      <td>
        <%= link_to 'View', project_path(project) %>
        <%= link_to 'Edit', edit_project_path(project) %>
        <%= link_to 'Delete', project_path(project), data: {:confirm => 'Are you sure?'}, :method => :delete %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>Projects#NEW</h1>

<%= render 'projects/formProjects' %>

app/views/projects/show.html.erb
<h1>Projects#show</h1>

<div class="card center" style="width: 18rem;">
  <div class="card-body">
    <h3 class="card-title"><strong><%= @project.title%></strong></h3>
    <h6 class="card-subtitle mb-2 text-muted">Managed by <%= @project.manager.username.capitalize %></h6>
    <p class="card-text"><%= @project.description %></p>
    <%= link_to 'Edit', edit_project_path(@project), class: "card-link" %>
    <%= link_to 'Delete', project_path(@project), data: {:confirm => 'Are you sure?'}, :method => :delete, class: "card-link" %>
  </div>
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/projects_users/_formProjectsUsers.html.erb
<%= form_for @project_user do |f| %>
  <p>
    <%= f.label 'Project' %>
    <%= f.select :project_id, options_for_select(@usernames)%>
  </p>
  
  <p>
    <%= f.label 'User' %>
    <%= f.select :user_id, options_for_select(@project_titles) %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects_users/edit.html.erb
<h1>ProjectsUsers#EDIT</h1>

<%= render 'projects_users/formProjectsUsers' %>

app/views/projects_users/index.html.erb
<h1>ProjectsUsers#INDEX</h1>

app/views/projects_users/new.html.erb
<h1>ProjectsUsers#NEW</h1>

<%= form_for @project_user do |f| %>
<p>
    <%= f.label 'Project' %>
    <%= f.integer_field :project_id %>
  </p>
  
  <p>
    <%= f.label 'User' %>
    <%= f.integer_field :user_id %>
  </p>

  
  
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%# <%= render 'projects_users/formProjectsUsers' %> %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <strong><%= link_to 'Bug Tracker', root_path, class: 'navbar-brand' %></strong>
  <%# <a class="navbar-brand" href="#">Bug Tracker</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
            Welcome, <%= current_user.username %>
          </a>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>